### ISSUE TITLE
Release GitHub Echo v1.0.0

### ISSUE THREAD

**Issue by AryanK1511** [AryanK1511/github-echo#50]
We’re preparing to release **v1.0.0** of GitHub Echo Tool, marking the first major release with significant improvements, added features, and updated documentation. This release includes breaking changes, new command structures, and a streamlined configuration approach, enhancing usability and flexibility.

**Tasks**

- [x] Refactor code to include three commands: `analyze`, `init`, and `delete-config`.
- [x] Improve prompt to give better insights that are more catered towards open-source contributors.
- [x] Remove Docker support and related documentation.
- [x] Implement improved error handling for the configuration file parsing and validation.
- [x] Update README, migration guide, and examples for **v1.0.0**.
- [x] Create a video GIF for README showcasing the tool in action.
